# Generated by Django 4.0.1 on 2022-01-31 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_remove_weeklybox_produce_weeklybox_produce'),
    ]

    operations = [
        migrations.AddField(
            model_name='produce',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklybox',
            name='farm_list',
            field=models.ManyToManyField(to='Api.Farmstead'),
        ),
    ]
