# Generated by Django 4.0.1 on 2022-02-02 03:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_produce_description_weeklybox_farm_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmstead',
            old_name='location',
            new_name='farmers_story',
        ),
        migrations.RemoveField(
            model_name='produce',
            name='farms',
        ),
        migrations.RemoveField(
            model_name='weeklybox',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='weeklybox',
            name='farm_list',
        ),
        migrations.RemoveField(
            model_name='weeklybox',
            name='name',
        ),
        migrations.AddField(
            model_name='farmstead',
            name='produces',
            field=models.ManyToManyField(to='Api.Produce'),
        ),
        migrations.AddField(
            model_name='farmstead',
            name='region',
            field=models.CharField(choices=[('Auckland', 'Auckland'), ('Northland', 'Northland'), ('Bay of Plenty', 'Bay of Plenty'), ('Waikato', 'Waikato'), ('Taranaki', 'Taranaki'), ('Hawkes Bay', 'Hawkes Bay'), ('Gisborne', 'Gisborne'), ('Manawatu-Wanganui', 'Manawatu-Wanganui'), ('Wellington', 'Wellington')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='produce',
            name='seasonal_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produce',
            name='storage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklybox',
            name='date_issued',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='weeklybox',
            name='region',
            field=models.CharField(choices=[('Auckland', 'Auckland'), ('Northland', 'Northland'), ('Bay of Plenty', 'Bay of Plenty'), ('Waikato', 'Waikato'), ('Taranaki', 'Taranaki'), ('Hawkes Bay', 'Hawkes Bay'), ('Gisborne', 'Gisborne'), ('Manawatu-Wanganui', 'Manawatu-Wanganui'), ('Wellington', 'Wellington')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='farmstead',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='weeklybox',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='weeklybox',
            name='produce',
        ),
        migrations.AddField(
            model_name='weeklybox',
            name='produce',
            field=models.JSONField(null=True),
        ),
    ]
