# Generated by Django 4.0.1 on 2022-02-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_rename_location_farmstead_farmers_story_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmstead',
            name='farmers_story',
            field=models.TextField(blank=True, null=True),
        ),
    ]
