# Generated by Django 4.0.2 on 2022-02-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_alter_farmstead_farmers_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmstead',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
