# Generated by Django 4.0.2 on 2022-02-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_farmstead_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='produce',
            name='additional_information',
            field=models.TextField(blank=True, null=True),
        ),
    ]
