# Generated by Django 4.0.2 on 2022-02-10 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0007_produce_additional_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklybox',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='farmstead',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='produce',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
