# Generated by Django 4.0.2 on 2022-02-10 22:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0008_weeklybox_day_alter_farmstead_id_alter_produce_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklybox',
            name='date_issued',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
