# Generated by Django 4.0.2 on 2022-02-10 22:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0010_alter_weeklybox_date_issued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklybox',
            name='date_issued',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 10, 22, 50, 28, 156182, tzinfo=utc)),
        ),
    ]
