# Generated by Django 4.0.2 on 2022-02-11 00:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0011_alter_weeklybox_date_issued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklybox',
            name='date_issued',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 11, 13, 18, 42, 642138)),
        ),
    ]
