# Generated by Django 4.0.2 on 2022-02-11 01:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0014_delete_image_produce_caption_produce_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produce',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produce',
            name='image',
            field=models.ImageField(null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='weeklybox',
            name='date_issued',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 11, 14, 27, 13, 63241)),
        ),
    ]
