# Generated by Django 4.0.2 on 2022-02-13 21:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0015_alter_produce_caption_alter_produce_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produce',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='weeklybox',
            name='date_issued',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 14, 10, 27, 52, 406259)),
        ),
    ]
