# Generated by Django 4.0.2 on 2022-02-13 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0017_alter_weeklybox_date_issued'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produce',
            name='caption',
        ),
        migrations.AddField(
            model_name='farmstead',
            name='image',
            field=models.ImageField(null=True, upload_to='farmstead_images/'),
        ),
        migrations.AlterField(
            model_name='produce',
            name='image',
            field=models.ImageField(null=True, upload_to='produce_images/'),
        ),
        migrations.AlterField(
            model_name='weeklybox',
            name='date_issued',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 14, 11, 30, 48, 591195)),
        ),
    ]
