# Generated by Django 4.0.2 on 2022-02-13 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0018_remove_produce_caption_farmstead_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklybox',
            name='date_issued',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 14, 12, 2, 44, 662769)),
        ),
    ]
