# Generated by Django 4.0.2 on 2022-02-14 01:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0021_alter_weeklybox_options_alter_weeklybox_date_issued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmstead',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='farmstead_images/'),
        ),
        migrations.AlterField(
            model_name='produce',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produce_images/'),
        ),
        migrations.AlterField(
            model_name='weeklybox',
            name='date_issued',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 14, 14, 0, 43, 729286)),
        ),
    ]
