# Generated by Django 4.0.2 on 2022-02-15 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0022_alter_farmstead_image_alter_produce_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklybox',
            name='date_issued',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 15, 17, 56, 44, 354804)),
        ),
    ]
